src: ext/{argon2_wrap/argon_*.c,phc-winner-argon2/src/{argon2.c,core.c,blake2/blake2b.c,thread.c,encoding.c,ref.c},argon2_wrap/pthread.c}
cflags: -I$GEM_HOME/ext/phc-winner-argon2/include -I$GEM_HOME/ext/phc-winner-argon2/src
out: lib/argon2/cext/argon2.su
