sudo: false

language: ruby

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - env: RUBY_STACK=jt PATH=$HOME/graalvm/jruby/bin:$HOME/graalvm/mx:$PATH JAVA_HOME=$HOME/graalvm/jdk
    - rvm: 2.3.1
      env: RUBY_STACK=rvm
    - rvm: jruby-9.1.2.0
      jdk: oraclejdk8
      env: RUBY_STACK=rvm
    - rvm: jruby-head
      jdk: oraclejdk8
      env: RUBY_STACK=rvm
    - rvm: 2.2.5
      env: RUBY_STACK=rvm

env:
  global: TEST_CHECKS=1

before_install:
  - unset JRUBY_OPTS

install:
  - bin/travis-setup

script:
  - if [ "$RUBY_STACK" = "jt" ]; then bin/test-jruby+truffle; else ruby test/jruby+truffle/run.rb; fi

after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
