sudo: false
language: java
jdk:
  - oraclejdk8
install:
  - mkdir "$HOME/graalvm" && cd "$HOME/graalvm"
  - git clone --depth 1 https://github.com/graalvm/mx
  - git clone --depth 1 https://github.com/graalvm/sulong
  - git clone --depth 1 https://github.com/jruby/jruby
  - wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/jvmci-0.17/jdk1.8.0_91-jvmci-0.17-linux-amd64.tar.gz
  - tar -xzf jdk1.8.0_91-jvmci-0.17-linux-amd64.tar.gz
  - export PATH="`pwd`/mx:$PATH"
  - export JAVA_HOME="`pwd`/jdk1.8.0_91-jvmci-0.17"
  - cd "$HOME/graalvm/sulong" && mx build
  - cd "$HOME/graalvm/jruby" && tool/jt.rb build
  - export PATH="`pwd`/bin:$PATH"
  - cd "$HOME/build/lxp/ruby-argon2" && bin/setup-jruby+truffle
script:
  - bin/test-jruby+truffle
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
